#pragma once


D3D12_GRAPHICS_PIPELINE_STATE_DESC MakeOpaquePipelineState();
D3D12_GRAPHICS_PIPELINE_STATE_DESC MakeMaskedPipelineState();
D3D12_GRAPHICS_PIPELINE_STATE_DESC MakeTransparentPipelineState();
D3D12_GRAPHICS_PIPELINE_STATE_DESC MakeDoubleSidedOpaquePipelineState();
D3D12_GRAPHICS_PIPELINE_STATE_DESC MakeDoubleSidedMaskedPipelineState();
D3D12_GRAPHICS_PIPELINE_STATE_DESC MakeDoubleSidedTransparentPipelineState();

D3D12_GRAPHICS_PIPELINE_STATE_DESC MakeDebugDrawPipelineState();